# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_hello2']

# Cell
def say_hello():
    return "Hello From Learnathon Module"

# Cell
def say_hello2():
    return "This is a test for new function"